version: '3.1'

services:

  dummy:
    container_name: dummy
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: dummy
    ports:
      - "1002:5005"
    command: rasa run --enable-api --log-file rasa.log --debug --cors "*"

  chitchat:
    container_name: chitchat
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: chitchat
    ports:
      - "1001:5005"
    command: rasa run --enable-api --log-file rasa.log --debug --cors "*" 

  kalani:
    container_name: kalani
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: kalani
    ports:
      - "1000:5005"
   

  hexaware:
   container_name: hexaware
   build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: kalani
   ports:
      - "1003:5005"
   command: rasa run --enable-api --log-file rasa.log --debug --cors "*"


  # hexaware:
  #  container_name: hexaware
  #  image: rasa-faq:latest
  #  ports:
  #    - "5005:5005"
  #  restart: always
  #  command: rasa run -m models/hexaware-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # organization:
  #   container_name: organization
  #   image: rasa-faq:latest
  #   ports:
  #     - "5000:5005"
  #   restart: always
  #   command: rasa run -m models/organization-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network
