version: '3.1'

services:

  common:
    container_name: common
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/chitchat/nlu.yml data/hexaware/nlu.yml data/chitchat/rules.yml data/hexaware/rules.yml data/chitchat/stories.yml data/hexaware/stories.yml -d data/hexaware/domain --config data/hexaware/config.yml
    ports:
      - "1001:5005"
    command: rasa run --enable-api --log-file rasa.log --debug --cors "*" 

  kalani:
    container_name: kalani
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/kalani/nlu.yml data/kalani/rules.yml data/kalani/stories.yml -d data/kalani/domain.yml --config data/kalani/config.yml --out ./models --fixed-model-name kalani
    ports:
      - "1000:5005"
    volumes:
      - "./shared/models:/app/shared"
    command: rasa run -m models/kalani.tar.gz --enable-api --log-file rasa.log --debug && ./actions-bg.sh

  hexaware:
   container_name: hexaware
   build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/chitchat/nlu.yml data/hexaware/nlu.yml data/chitchat/rules.yml data/hexaware/rules.yml data/chitchat/stories.yml data/hexaware/stories.yml -d data/hexaware/domain --config data/hexaware/config.yml
   ports:
      - "1003:5005"
   command: rasa run --enable-api --log-file rasa.log --debug --cors "*"







  # dummy:
  #   container_name: dummy
  #   build: 
  #     context: ./docker
  #     dockerfile: Dockerfile
  #     args:
  #       org: rasa train --data data/chitchat/nlu.yml data/hexaware/nlu.yml data/chitchat/rules.yml data/hexaware/rules.yml data/chitchat/stories.yml data/hexaware/stories.yml -d data/hexaware/domain --config data/hexaware/config.yml
  #   ports:
  #     - "1002:5005"
  #   command: rasa run --enable-api --log-file rasa.log --debug --cors "*"


  # hexaware:
  #  container_name: hexaware
  #  image: rasa-faq:latest
  #  ports:
  #    - "5005:5005"
  #  restart: always
  #  command: rasa run -m models/hexaware-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # organization:
  #   container_name: organization
  #   image: rasa-faq:latest
  #   ports:
  #     - "5000:5005"
  #   restart: always
  #   command: rasa run -m models/organization-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network
