version: '3.1'

services:

  dummy:
    container_name: dummy
    image: rasa-evis:latest
    build: ./docker
    ports:
      - "1001:5005"
    command: rasa run -m models/20230407-142457-chitchat.tar.gz --enable-api --log-file rasa.log --debug --cors "*"

  chitchat:
    container_name: chitchat
    image: rasa-evis:latest
    build: ./docker
    ports:
      - "1000:5005"
    command: rasa run -m models/20230407-142457-chitchat.tar.gz --enable-api --log-file rasa.log --debug --cors "*" 

  kalani:
    container_name: kalani
    image: rasa-evis:latest
    build: ./docker
    ports:
      - "1000:5005"
    command: rasa run --enable-api --log-file rasa.log --debug --cors "*"

  hexaware:
   container_name: hexaware
   image: rasa-evis:latest
   build: ./docker
   ports:
     - "1000:5005"
   command: rasa run -m models/20230407-142457-chitchat.tar.gz --enable-api --log-file rasa.log --debug --cors "*"


  # hexaware:
  #  container_name: hexaware
  #  image: rasa-faq:latest
  #  ports:
  #    - "5005:5005"
  #  restart: always
  #  command: rasa run -m models/hexaware-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # organization:
  #   container_name: organization
  #   image: rasa-faq:latest
  #   ports:
  #     - "5000:5005"
  #   restart: always
  #   command: rasa run -m models/organization-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network
