version: '3.1'

services:

  common:
    container_name: common
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/chitchat/nlu.yml data/evis/nlu.yml data/chitchat/rules.yml data/evis/rules.yml data/chitchat/stories.yml data/evis/stories.yml -d data/evis/domain --config data/evis/config.yml
    ports:
      - "1001:5005"
    command: rasa run --enable-api --log-file rasa.log --debug --cors "*" 

  kalani:
    container_name: kalani
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/kalani/nlu.yml data/kalani/rules.yml data/kalani/stories.yml -d data/kalani/domain.yml --config data/kalani/config.yml --out ./models --fixed-model-name kalani
    ports:
      - "1000:5005"
    volumes:
      - "./shared/models:/app/shared"
    command: rasa run -m models/kalani.tar.gz --enable-api --log-file rasa.log --debug --cors "*" && ./actions-bg.sh

  evisalone:
    container_name: evisalone
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/evis/nlu.yml data/evis/rules.yml data/evis/stories.yml -d data/evis/domain.yml --config data/evis/config.yml --out ./models --fixed-model-name evisalone
    ports:
      - "1006:5005"
    volumes:
      - "./shared/models:/app/shared"
    command: rasa run -m models/evisalone.tar.gz --enable-api --log-file rasa.log --debug --cors "*"


  evis:
    container_name: evis
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        org: rasa train --data data/gunjan/nlu.yml data/evis/nlu.yml data/gunjan/rules.yml data/evis/rules.yml data/gunjan/stories.yml data/evis/stories.yml --config data/evis/config.yml -d data/evis/domain --out ./models --fixed-model-name evis
    ports:
      - "1003:5005"
    volumes:
      - "./shared/models:/app/shared"
    command: rasa run -m models/evis.tar.gz --enable-api --log-file rasa.log --debug --cors "*"


















  # dummy:
  #   container_name: dummy
  #   build: 
  #     context: ./docker
  #     dockerfile: Dockerfile
  #     args:
  #       org: rasa train --data data/chitchat/nlu.yml data/evis/nlu.yml data/chitchat/rules.yml data/evis/rules.yml data/chitchat/stories.yml data/evis/stories.yml -d data/evis/domain --config data/evis/config.yml
  #   ports:
  #     - "1002:5005"
  #   command: rasa run --enable-api --log-file rasa.log --debug --cors "*"


  # evis:
  #  container_name: evis
  #  image: rasa-faq:latest
  #  ports:
  #    - "5005:5005"
  #  restart: always
  #  command: rasa run -m models/evis-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # organization:
  #   container_name: organization
  #   image: rasa-faq:latest
  #   ports:
  #     - "5000:5005"
  #   restart: always
  #   command: rasa run -m models/organization-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network
