apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: rasa
  labels:
    app: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      namespace: rasa
      labels:
        app: rasa
    spec:
      containers:
        - name: rasa
          image: localhost:5005/rasa
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          readinessProbe:
            httpGet:
              path: /
              port: 5005
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: rasa-
